const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const migrationDirectory = path.join(root, 'supabase', 'migrations');
const schemaMigrationName = fs
  .readdirSync(migrationDirectory)
  .find((fileName) => fileName.endsWith('_identity_access_schema.sql'));

assert.ok(schemaMigrationName, 'The identity-access schema migration must exist');

const schemaMigration = fs.readFileSync(
  path.join(migrationDirectory, schemaMigrationName),
  'utf8'
);
const plan = fs.readFileSync(
  path.join(
    root,
    'docs',
    'superpowers',
    'plans',
    '2026-08-20-trustos-phase-2-identity-access.md'
  ),
  'utf8'
);

test('the deployed schema migration provisions both canonical modules without fictional tenants', () => {
  assert.match(
    schemaMigration,
    /insert into public\.module_catalog \(id, name, status\) values\s*\('trustops', 'TrustOps Core', 'active'\),\s*\('grantflow', 'GrantFlow', 'active'\)\s*on conflict do nothing;/
  );
  assert.doesNotMatch(schemaMigration, /Fictional Client [AB]/);
});

test('the initial TrustOS migration refuses a database that already contains application tables', () => {
  assert.match(schemaMigration, /TrustOS project boundary check failed/);
  assert.match(schemaMigration, /from pg_catalog\.pg_tables/);
  assert.match(schemaMigration, /where schemaname = 'public'/);
});

test('the initial TrustOS migration records the dedicated project identity privately', () => {
  assert.match(schemaMigration, /create table private\.instance_identity/);
  assert.match(schemaMigration, /napjcycxzyrsruiifuca/);
  assert.match(schemaMigration, /revoke all on table private\.instance_identity from public, anon, authenticated/);
});

test('the initial TrustOS migration revokes automatic public API privileges before application tables are created', () => {
  const revokePosition = schemaMigration.indexOf(
    'alter default privileges for role postgres in schema public'
  );
  const firstTablePosition = schemaMigration.indexOf('create table public.organizations');

  assert.ok(revokePosition >= 0, 'default privilege revocation must be present');
  assert.ok(firstTablePosition >= 0, 'TrustOS application tables must be present');
  assert.ok(
    revokePosition < firstTablePosition,
    'default API privileges must be revoked before TrustOS application tables are created'
  );
});

test('every downstream migration is generated by the CLI after the schema migration', () => {
  const downstreamSuffixes = [
    'identity_access_rls',
    'audit_append',
    'invitation_acceptance',
    'platform_admin',
    'team_admin',
    'security_operations'
  ];

  for (const suffix of downstreamSuffixes) {
    assert.match(
      plan,
      new RegExp(`npx supabase migration new ${suffix} --workdir \\.\\.`),
      `Missing CLI generation instruction for ${suffix}`
    );
  }

  assert.doesNotMatch(
    plan,
    /supabase\/migrations\/20260820000[2-7]_[a-z_]+\.sql/,
    'The plan must not instruct executors to create migrations older than the schema migration'
  );
});
