const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const migrationDirectory = path.join(root, 'supabase', 'migrations');
const migrationNames = fs.readdirSync(migrationDirectory).sort();
const schemaMigrationName = migrationNames.find((fileName) =>
  fileName.endsWith('_identity_access_schema.sql')
);
const instanceGuardMigrationName = migrationNames.find((fileName) =>
  fileName.endsWith('_trustos_instance_guard.sql')
);

assert.ok(schemaMigrationName, 'The identity-access schema migration must exist');
assert.ok(instanceGuardMigrationName, 'The permanent TrustOS instance-guard migration must exist');

const schemaMigration = fs.readFileSync(
  path.join(migrationDirectory, schemaMigrationName),
  'utf8'
);
const instanceGuardMigration = fs.readFileSync(
  path.join(migrationDirectory, instanceGuardMigrationName),
  'utf8'
);
const plan = fs.readFileSync(
  path.join(
    root,
    'docs',
    'superpowers',
    'plans',
    '2026-08-20-trustos-phase-2-identity-access.md'
  ),
  'utf8'
);

test('the deployed schema migration provisions both canonical modules without fictional tenants', () => {
  assert.match(
    schemaMigration,
    /insert into public\.module_catalog \(id, name, status\) values\s*\('trustops', 'TrustOps Core', 'active'\),\s*\('grantflow', 'GrantFlow', 'active'\)\s*on conflict do nothing;/
  );
  assert.doesNotMatch(schemaMigration, /Fictional Client [AB]/);
});

test('the initial TrustOS migration refuses a database that already contains application tables', () => {
  assert.match(schemaMigration, /TrustOS project boundary check failed/);
  assert.match(schemaMigration, /from pg_catalog\.pg_tables/);
  assert.match(schemaMigration, /where schemaname = 'public'/);
});

test('the initial TrustOS migration records the dedicated project identity privately', () => {
  assert.match(schemaMigration, /create table private\.instance_identity/);
  assert.match(schemaMigration, /napjcycxzyrsruiifuca/);
  assert.match(schemaMigration, /revoke all on table private\.instance_identity from public, anon, authenticated/);
});

test('the initial TrustOS migration revokes automatic public API privileges before application tables are created', () => {
  const revokePosition = schemaMigration.indexOf(
    'alter default privileges for role postgres in schema public'
  );
  const firstTablePosition = schemaMigration.indexOf('create table public.organizations');

  assert.ok(revokePosition >= 0, 'default privilege revocation must be present');
  assert.ok(firstTablePosition >= 0, 'TrustOS application tables must be present');
  assert.ok(
    revokePosition < firstTablePosition,
    'default API privileges must be revoked before TrustOS application tables are created'
  );
});

test('the permanent instance guard is private, exact-project pinned and unavailable to application roles', () => {
  assert.match(instanceGuardMigration, /create or replace function private\.assert_trustos_instance\(\)/);
  assert.match(instanceGuardMigration, /napjcycxzyrsruiifuca/);
  assert.match(instanceGuardMigration, /security invoker/);
  assert.match(instanceGuardMigration, /set search_path = ''/);
  assert.match(
    instanceGuardMigration,
    /revoke all on function private\.assert_trustos_instance\(\) from public, anon, authenticated, service_role;/
  );
  assert.match(
    instanceGuardMigration,
    /grant execute on function private\.assert_trustos_instance\(\) to postgres;/
  );
});

test('every migration created after the permanent guard must assert the TrustOS instance first', () => {
  const guardIndex = migrationNames.indexOf(instanceGuardMigrationName);
  const laterMigrations = migrationNames.slice(guardIndex + 1);

  for (const migrationName of laterMigrations) {
    const migration = fs.readFileSync(path.join(migrationDirectory, migrationName), 'utf8');
    assert.match(
      migration,
      /^\s*select\s+private\.assert_trustos_instance\(\);/i,
      `${migrationName} must fail closed unless it is running on the dedicated TrustOS Supabase instance`
    );
  }
});

test('every downstream migration is generated by the CLI after the schema migration', () => {
  const downstreamSuffixes = [
    'identity_access_rls',
    'audit_append',
    'invitation_acceptance',
    'platform_admin',
    'team_admin',
    'security_operations'
  ];

  for (const suffix of downstreamSuffixes) {
    assert.match(
      plan,
      new RegExp(`npx supabase migration new ${suffix} --workdir \\.\\.`),
      `Missing CLI generation instruction for ${suffix}`
    );
  }

  assert.doesNotMatch(
    plan,
    /supabase\/migrations\/20260820000[2-7]_[a-z_]+\.sql/,
    'The plan must not instruct executors to create migrations older than the schema migration'
  );
});
